audiotest/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

app_name = "audiotest"

urlpatterns = [
    path('', views.index, name='index'),
    path('interview', views.interview, name='interview'),
    path('interview/setting', views.interview_question_setting, name='setting'),
    path('mypage/privacy', views.mypage_privacy, name='privacy'),
    path('interview/main', views.get_post, name='main'),
    path('change_password/', views.change_password, name="re_password"),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from docu.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('audiotest.urls')),
    path('docu/', include('docu.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

docu/urls.py
from django.urls import path
from . import views
from docu.views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'docu'

urlpatterns = [
    # base_views.py
    path('',
         base_views.index, name='index'),
    path('<int:question_id>/',
         base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/',
         comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
         comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
         comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/',
         comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/',
         comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/',
         comment_views.comment_delete_answer, name='comment_delete_answer'),

# vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
]

docu/models.py
from django.db import models
from django.contrib.auth.models import User

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')  # 추천인 추가


    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)

docu/forms.py
from django import forms
from docu.models import Question, Answer, Comment

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '내용',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글 내용',
        }

docu/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer

@login_required(login_url='common:login')
def answer_create(request, question_id):
    """
    docu 답변 등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('docu:detail', question_id=question_id)

    else:
        form = AnswerForm()
    context = {'question': question, 'form':form}
    return render(request, 'docu/question_detail.html', context)

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """
    docu 답변수정
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정 권한이 없습니다')
        return redirect('docu:detail', question_id=answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('docu:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'docu/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """
    docu 답변 삭제
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제 권한이 없습니다')
    else:
        answer.delete()
    return redirect('docu:detail', question_id=answer.question.id)

docu/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from ..models import Question
from django.db.models import Q, Count

def index(request):
    """
    docu 목록 출력
    """
    # 입력
    page = request.GET.get('page', '1') #페이지
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recommend')  # 정렬 기준

    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:  # recent
        question_list = Question.objects.order_by('-create_date')

    # 조회
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) | # 내용 검색
            Q(author__username__icontains=kw)  # 질문 글쓴이 검색
        ).distinct()

    # 페이징 처리
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {'question_list':page_obj, 'page': page, 'kw': kw, 'so': so} #page, kw, so 추가
    return render(request, 'docu/question_list.html', context)

def detail(request, question_id):
    """
    docu 내용 출력
    """
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question':question}
    return render(request, 'docu/question_detail.html', context)

docu/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import CommentForm
from ..models import Question, Answer, Comment

@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    """
    docu 질문 댓글 등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('docu:detail', question_id=comment.question.id), comment.id))
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'docu/comment_form.html', context)

@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    """
    docu 질문 댓글 수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 수정 권한이 없습니다')
        return redirect('docu:detail', question_id=comment.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('docu:detail', question_id=comment.question.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'docu/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    """
    docu 질문 댓글 삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 삭제 권한이 없습니다')
        return redirect('docu:detail', question_id=comment.question.id)
    else:
        comment.delete()
    return redirect('docu:detail', question_id=comment.question.id)

@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    """
    docu 답글 댓글 등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('docu:detail', question_id=comment.answer.question.id), comment.id))
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'docu/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    """
    docu 답글 댓글 수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('docu:detail', question_id=comment.answer.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('docu:detail', question_id=comment.answer.question.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'docu/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    """
    docu 답글 댓글 삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 삭제 권한이 없습니다')
        return redirect('docu:detail', question_id=comment.answer.question.id)
    else:
        comment.delete()
    return redirect('docu:detail', question_id=comment.answer.question.id)

docu/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question

@login_required(login_url='common:login')
def question_create(request):
    """
    docu 질문 등록
    """
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('docu:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'docu/question_form.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    """
    docu 질문수정
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('docu:detail', question_id=question.id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('docu:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'docu/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    """
    docu 질문삭제
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제 권한이 없습니다')
        return redirect('docu:detail', question_id=question.id)
    question.delete()
    return redirect('docu:index')

docu/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from ..models import Question


@login_required(login_url='common:login')
def vote_question(request, question_id):
    """
    docu 질문 추천 등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다')
    else:
        question.voter.add(request.user)
    return redirect('docu:detail', question_id=question.id)

templates/docu/answer_form.html
{% extends 'mainpage.html' %}

{% block content %}
<section id="header">
    <h1><a href="{% url 'index' %}">jUmP</a></h1>
    <nav id="nav">
        <ul>
            <li id="btn_home"><a href="{% url 'audiotest:index' %}">Home</a></li>
            <li id="btn_interview"><a href="{% url 'audiotest:interview' %}">Interview</a></li>
            <li class="current" id="btn_employment_info"><a href="{% url 'docu:index' %}">Employment info.</a></li>
            {% if user.is_authenticated %}
            <li id="btn_mypage"><a href="{% url 'audiotest:privacy' %}">Mypage</a></li>
            <li id="btn_logout"><a href="{% url 'audiotest:logout' %}">Logout</a></li>
            {% else %}
            <li id="btn_login"><a href="{% url 'audiotest:login' %}">Login</a></li>
            {% endif %}
        </ul>
    </nav>
</section>
<section id="main">
    <div class="container">
        <article class="box post">
            <div class="container my-3">
                <form method="post" class="post-form">
                    {% csrf_token %}
                    {% include "form_errors.html" %}
                    <div class="form-group">
                        <label for="content">답변 내용</label>
                        <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">저장하기</button>
                </form>
            </div>
        </article>
    </div>
</section>

{% endblock %}

templates/docu/comment_form.html
{% extends 'mainpage.html' %}


{% block content %}
<section id="header">
    <h1><a href="{% url 'index' %}">jUmP</a></h1>
    <nav id="nav">
        <ul>
            <li id="btn_home"><a href="{% url 'audiotest:index' %}">Home</a></li>
            <li id="btn_interview"><a href="{% url 'audiotest:interview' %}">Interview</a></li>
            <li class="current" id="btn_employment_info"><a href="{% url 'docu:index' %}">Employment info.</a></li>
            {% if user.is_authenticated %}
            <li id="btn_mypage"><a href="{% url 'audiotest:privacy' %}">Mypage</a></li>
            <li id="btn_logout"><a href="{% url 'audiotest:logout' %}">Logout</a></li>
            {% else %}
            <li id="btn_login"><a href="{% url 'audiotest:login' %}">Login</a></li>
            {% endif %}
        </ul>
    </nav>
</section>
<section id="main">
    <div class="container">
        <article class="box post">
            <div class="container my-3">
                <h5 class="border-bottom pb-2">댓글 등록하기</h5>
                <form method="post" class="post-form my-3">
                    {% csrf_token %}
                    {% include "form_errors.html" %}
                    <div class="form-group">
                        <label for="content">댓글 내용</label>
                        <textarea class="form-control"name="content" id="content" rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">저장하기</button>
                </form>
            </div>
        </article>
    </div>
</section>
{% endblock %}

templates/docu/question_detail.html
{% extends 'mainpage.html' %}

{% block content %}

<section id="header">
    <h1><a href="{% url 'index' %}">jUmP</a></h1>
    <nav id="nav">
        <ul>
            <li id="btn_home"><a href="{% url 'audiotest:index' %}">Home</a></li>
            <li id="btn_interview"><a href="{% url 'audiotest:interview' %}">Interview</a></li>
            <li class="current" id="btn_employment_info"><a href="{% url 'docu:index' %}">Employment info.</a></li>
            {% if user.is_authenticated %}
            <li id="btn_mypage"><a href="{% url 'audiotest:privacy' %}">Mypage</a></li>
            <li id="btn_logout"><a href="{% url 'audiotest:logout' %}">Logout</a></li>
            {% else %}
            <li id="btn_login"><a href="{% url 'audiotest:login' %}">Login</a></li>
            {% endif %}
        </ul>
    </nav>
</section>
<section id="main">
    <div class="container">
        <article class="box post">
            <div class = "container my-3">
                <!--사용자 오류-->
                {% if messages %}
                <div class = "alert alert-danger my-3" role="alert">
                {% for message in messages %}
                    <strong>{{ message.tags }}</strong>
                    <ul><li>{{ message.message }}</li></ul>
                    {% endfor %}
                </div>
                {% endif %}
                <h2 class = "border-bottom py-2">{{ question.subject }}</h2>
                <div class="row my-3">
                    <div class="col-1"> <!-- 추천 영역 -->
                        <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{question.voter.count}}</div>
                        <a href="#" data-uri="{% url 'docu:vote_question' question.id  %}"
                           class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
                    </div>
                    <div class="col-11"> <!-- 질문 영역 -->
                        <!-- 기존 내용 -->
                        <div class = "card my-3">
                            <div class = "card-body">
                                <div class = "card-text" style = "white-space: pre-line;">
                                    {{ question.content }}
                                </div>
                                <div class = "d-flex justify-content-end">
                                    {% if question.modify_date %}
                                    <div class="badge bg-light p-2 text-left text-dark mx-3">
                                        <div class="mb-2">modified at</div>
                                        <div>{{ question.modify_date }}</div>
                                    </div>
                                    {% endif %}
                                    <div class = "badge bg-light p-2 text-left text-dark">
                                        <div class="mb-2">{{ question.author.username }}</div>
                                        <div>{{ question.create_date }}</div>
                                    </div>
                                </div>
                                {% if request.user == question.author %}
                                <div class="my-3">
                                    <a href="{% url 'docu:question_modify' question.id  %}"
                                       class="btn btn-sm btn-outline-secondary">수정</a>
                                    <a href="#" class="delete btn btn-sm btn-outline-secondary"
                                       data-uri="{% url 'docu:question_delete' question.id %}">삭제</a>
                                </div>
                                {% endif %}
                                <!-- 질문 댓글 Start -->
                                {% if question.comment_set.count > 0 %}
                                <div class="mt-3">
                                    {% for comment in question.comment_set.all %}  <!-- 등록한 댓글을 출력 -->
                                    <a name="comment_{{ comment.id }}"></a>
                                    <div class="comment py-2 text-muted">  <!-- 댓글 각각에 comment 스타일 지정 -->
                                        <span style="white-space: pre-line;">{{ comment.content }}</span>
                                        <span>
                                            - {{ comment.author }}, {{ comment.create_date }}
                                            {% if comment.modify_date %}
                                            (수정:{{ comment.modify_date }})
                                            {% endif %}
                                        </span>
                                        {% if request.user == comment.author %}
                                        <a href="{% url 'docu:comment_modify_question' comment.id  %}" class="small">수정</a>
                                        <a href="#" class="small delete" data-uri="{% url 'docu:comment_delete_question' comment.id  %}">삭제</a>
                                        {% endif %}
                                    </div>
                                    {% endfor %}
                                </div>
                                {% endif %}
                                <div>
                                    <a href="{% url 'docu:comment_create_question' question.id  %}" class="small"><small>댓글 추가</small></a>
                                    <!-- 댓글 추가 링크 -->
                                </div>
                                <!-- 질문 댓글 End -->
                            </div>
                        </div>
                    </div>
                </div>
                <h5 class = "border-bottom my-3 py-2">
                    {{ question.answer_set.count}}개의 답변이 있습니다.
                </h5>
                {% for answer in question.answer_set.all %}
                    <!-- 기존 내용 -->
                    <div class = "card my-3">
                        <div class = "card-body">
                            <div class = "card-text" style = "white-space: pre-line;">
                                {{ answer.content }}
                            </div>
                            <div class = "d-flex justify-content-end">
                                {% if answer.modify_date %}
                                <div class="badge bg-light p-2 text-left text-dark mx-3">
                                    <div class="mb-2">modified at</div>
                                    <div>{{ answer.modify_date }}</div>
                                </div>
                                {% endif %}
                                <div class = "badge bg-light p-2 text-left text-dark">
                                    <div class="mb-2">{{ answer.author.username }}</div>
                                    <div>{{ answer.create_date }}</div>
                                </div>
                            </div>
                            {% if request.user == answer.author %}
                            <div class="my-3">
                                <a href="{% url 'docu:answer_modify' answer.id  %}"
                                   class="btn btn-sm btn-outline-secondary">수정</a>
                                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                                   data-uri="{% url 'docu:answer_delete' answer.id  %}">삭제</a>
                            </div>
                            {% endif %}
                            <!-- 답변 댓글 시작 -->
                            {% if answer.comment_set.count > 0 %}
                            <div class="mt-3">
                                {% for comment in answer.comment_set.all %}
                                <div class="comment py-2 text-muted">
                                    <span style="white-space: pre-line;">{{ comment.content }}</span>
                                    <span>
                                        - {{ comment.author }}, {{ comment.create_date }}
                                        {% if comment.modify_date %}
                                        (수정:{{ comment.modify_date }})
                                        {% endif %}
                                    </span>
                                    {% if request.user == comment.author %}
                                    <a href="{% url 'docu:comment_modify_answer' comment.id  %}" class="small">수정</a>
                                    <a href="#" class="small delete" data-uri="{% url 'docu:comment_delete_answer' comment.id  %}">삭제</a>
                                    {% endif %}
                                </div>
                                {% endfor %}
                            </div>
                            {% endif %}
                            <div>
                                <a href="{% url 'docu:comment_create_answer' answer.id  %}" class="small"><small>댓글 추가</small></a>
                            </div>
                            <!-- 답변 댓글 끝 -->
                        </div>
                    </div>
                {% endfor %}
                <form action = "{% url 'docu:answer_create' question.id %}" method = "post" class = "my-3">
                    {% csrf_token %}
                    {% if form.errors %}
                    <div class = "alert alert-danger" role = "alert">
                        {% for field in form %}
                        {% if field.errors %}
                        <strong>{{ field.label }}</strong>
                        {{ field.errors }}
                        {% endif %}
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div class = "form-group">
                        <textarea name ="content" id="content" {% if not user.is_authenticated %}disabled{% endif %} class = "form-control" rows="10"></textarea>
                    </div>
                    <button class="btn btn-secondary" type="submit" style = "margin-top:10px;">답변 등록</button>
                    <button class="btn btn-secondary" type="button" style = "float:right; margin-top:10px;" onClick="history.go(-1)">이전</button>
                </form>
            </div>
        </article>
    </div>
</section>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $(".recommend").on('click', function() {
        if(confirm("추천하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}