audiotest/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

app_name = "audiotest"

urlpatterns = [
    path('', views.index, name='index'),
    path('interview', views.interview, name='interview'),
    path('interview/setting', views.interview_question_setting, name='setting'),
    path('mypage/privacy', views.mypage_privacy, name='privacy'),
    path('interview/main', views.get_post, name='main'),
    path('change_password/', views.change_password, name="re_password"),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from docu.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('audiotest.urls')),
    path('docu/', include('docu.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

docu/urls.py
from django.urls import path
from . import views
from docu.views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'docu'

urlpatterns = [
    # base_views.py
    path('',
         base_views.index, name='index'),
    path('<int:question_id>/',
         base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/',
         comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
         comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
         comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/',
         comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/',
         comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/',
         comment_views.comment_delete_answer, name='comment_delete_answer'),

# vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
]

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/index.html
{% extends "mainpage.html" %}

{% block content %}

<section id="header">
    <h1><a href="{% url 'index' %}">jUmP</a></h1>
    <nav id="nav">
        <ul>
            <li class="current" id="btn_home"><a href="{% url 'audiotest:index' %}">Home</a></li>
            <li id="btn_interview"><a href="{% url 'audiotest:interview' %}">Interview</a></li>
            <li id="btn_employment_info"><a href="{% url 'docu:index' %}">Employment info.</a></li>
            {% if user.is_authenticated %}
            <li id="btn_mypage"><a href="{% url 'audiotest:privacy' %}">Mypage</a></li>
            <li id="btn_logout"><a href="{% url 'audiotest:logout' %}">Logout</a></li>
            {% else %}
            <li id="btn_login"><a href="{% url 'audiotest:login' %}">Login</a></li>
            {% endif %}
        </ul>
    </nav>
    <section id="banner_interview" style="height: 488.8px;">
    </section>
    <section id="intro" class="container">
        <div class="row">
            <div class="col-4 col-12-medium">
                <section class="first">
                    <i class="icon solid"><img src="static/img/monitoring.png" style="width:20em;"></i>
                    <header>
                        <h2>셀프 모니터링</h2>
                    </header>
                    <p>언제까지 핸드폰으로 모니터링 할래?</p>
                </section>
            </div>
            <div class="col-4 col-12-medium">
                <section class="middle" >
                    <i class="icon solid"><img src="static/img/survey.png" style="width:20em;"></i>
                    <header>
                        <h2>난이도별 질문 선정</h2>
                    </header>
                    <p>Step by Step! 단계별로 올라가기!</p>
                </section>
            </div>
            <div class="col-4 col-12-medium">
                <section class="last">
                    <i class="icon solid"><img src="static/img/logo.png" style="width:20em;"></i>
                    <header>
                        <h2>IT특화 질문</h2>
                    </header>
                    <p>같아가자 네카라쿠배!</p>
                </section>
            </div>
        </div>
    </section>
</section>

{% endblock %}

templates/interview.html
{% extends "mainpage.html" %}

{% block content%}

<section id="header">
    <h1><a href="{% url 'index' %}">jUmP</a></h1>
    <nav id="nav">
        <ul>
            <li id="btn_home"><a href="{% url 'audiotest:index' %}">Home</a></li>
            <li class="current" id="btn_interview"><a href="{% url 'audiotest:interview' %}">Interview</a></li>
            <li id="btn_employment_info"><a href="{% url 'docu:index' %}">Employment info.</a></li>
            {% if user.is_authenticated %}
            <li id="btn_mypage"><a href="{% url 'audiotest:privacy' %}">Mypage</a></li>
            <li id="btn_logout"><a href="{% url 'audiotest:logout' %}">Logout</a></li>
            {% else %}
            <li id="btn_login"><a href="{% url 'audiotest:login' %}">Login</a></li>
            {% endif %}
        </ul>
    </nav>
    <section id="banner_interview">
        <header style="background-color: white;">
            <h1>우리는 올라갈 일만 남았다.</h1>
            <p>#jUmP_UP</p>
            <br>
            <button type="button" class="setting_button" onclick="location.href='{% url 'audiotest:setting' %}'">면접 세팅</button>
        </header>
    </section>
</section>

{% endblock %}

templates/interview_main.html
{% extends "mainpage.html" %}

{% block content%}

<section id="header">
    <h1><a href="{% url 'audiotest:index' %}">jUmP</a></h1>
    <nav id="nav">
        <ul>
            <li id="btn_home"><a href="{% url 'audiotest:index' %}">Home</a></li>
            <li class="current" id="btn_interview"><a href="{% url 'audiotest:interview' %}">Interview</a></li>
            <li id="btn_employment_info"><a href="{% url 'docu:index' %}">Employment info.</a></li>
            {% if user.is_authenticated %}
            <li id="btn_mypage"><a href="{% url 'audiotest:privacy' %}">Mypage</a></li>
            <li id="btn_logout"><a href="{% url 'audiotest:logout' %}">Logout</a></li>
            {% else %}
            <li id="btn_login"><a href="{% url 'audiotest:login' %}">Login</a></li>
            {% endif %}
        </ul>
    </nav>
</section>
<section id="main">
    <div class="container">
        <div class="row">
            <div class="col-5 col-12-medium">

                <!-- Sidebar -->
                    <section class="box">
                        <video playsinline muted id="record_video" autoplay style="width: 29em;"></video>
                    </section>
                    <section class="box">
                        <header>
                            <h3>녹화영상 재생</h3>
                        </header>
                        <video playsinline id="replay_video" style="width: 29em;"></video>
                    </section>

            </div>
            <div class="col-7 col-12-medium imp-medium">
                <!-- Content -->
                    <article class="box post">
                        <div class="interview-buttons">
                            <button id="record"> Record </button>
                            <button id="stop"> Stop </button>
                            <button id="play"> Play </button>
                            <button id="download"> Download </button>
                            <span class="time_table"><b> 남은 시간: <span class="time" id="time"></span></b></span>
                        </div>
                        <b>
                        {% if question_list %}
                        <ul>
                            <br>
                            인성 질문
                            <br>
                            <br>
                            {% for question in question_list %}
                            {{ forloop.counter }}.
                            {{ question.question_text }}
                            <br>
                            <br>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        {% if question_list1 %}
                        <ul>
                            기술 질문
                            <br>
                            <br>
                            {% for question in question_list1 %}
                            {{ forloop.counter }}.
                            {{ question.question_text }}
                            <br>
                            <br>
                            {% endfor %}
                            </ul>
                        {% endif %}
                        <b> 
                    </article>

            </div>
        </div>
</section>
<script type="text/javascript">
    window.onload = function () {

        // 타이머 관련 설정
        document.getElementById("time").innerText = "90초";
        let timee = 90;
        // 타이머 함수
        let timer_output = function() {
            timee = timee - 1;
            document.getElementById("time").innerText = String(timee) + "초";
            if (timee <= 0) {
                clearInterval(timer);
            }
        }
        
        let timer;

        // 녹화 관련 변수 생성
        const parts = []; // 프레임 저장용 array
        let mediaRecorder; 
        let url;

        // 웹캠 화면 출력 및 녹화 시작
        navigator.mediaDevices.getUserMedia({ audio: true, video: true }).then(stream => {
        document.getElementById("record_video").srcObject = stream;
        document.getElementById("record").onclick = function () {
            mediaRecorder = new MediaRecorder(stream);
            timer = setInterval(timer_output, 1000);
            mediaRecorder.start(0);
            mediaRecorder.ondataavailable = function (e) {
                parts.push(e.data);
                if (timee <= 0) {
                    mediaRecorder.stop(0);
                    const blob = new Blob(parts, {
                        type: "video/webm"
                    });
                    url = URL.createObjectURL(blob);
                    setTimeout(function() {
                        document.getElementById("time").innerText = "90초";
                    }, 1000);
                }
                }
            }
        });

        // 녹화 중지
        document.getElementById("stop").onclick = function () {
            clearInterval(timer);
            document.getElementById("time").innerText = "90초";
            mediaRecorder.stop(0);
            const blob = new Blob(parts, {
                type: "video/webm"
            });
            url = URL.createObjectURL(blob);
        }


        // 녹화영상 재생
        document.getElementById("play").onclick = function () {
            document.getElementById("replay_video").srcObject = null;
            document.getElementById("replay_video").src = url;
            document.getElementById("replay_video").controls = true;
            document.getElementById("replay_video").play();
        }


        // 녹화영상 다운로드
        document.getElementById("download").onclick = function () {
            const videooo = document.createElement("a");
            document.body.appendChild(videooo);
            videooo.href = url;
            videooo.download = "interview_video.webm";
            videooo.click();
        }
    }
</script>

{% endblock %}

templates/interview_question_setting.html
{% extends "mainpage.html" %}

{% block content %}

<section id="header">
    <h1><a href="{% url 'index' %}">jUmP</a></h1>
    <nav id="nav">
        <ul>
            <li id="btn_home"><a href="{% url 'audiotest:index' %}">Home</a></li>
            <li class="current" id="btn_interview"><a href="{% url 'audiotest:interview' %}">Interview</a></li>
            <li id="btn_employment_info"><a href="{% url 'docu:index' %}">Employment info.</a></li>
            {% if user.is_authenticated %}
            <li id="btn_mypage"><a href="{% url 'audiotest:privacy' %}">Mypage</a></li>
            <li id="btn_logout"><a href="{% url 'audiotest:logout' %}">Logout</a></li>
            {% else %}
            <li id="btn_login"><a href="{% url 'audiotest:login' %}">Login</a></li>
            {% endif %}
        </ul>
    </nav>
<script>
        function send(){
            alert("제출되었습니다.");
            document.getElementById("contents").submit();
        }
</script>
</section>
<section id="main">
    <div class="container">
        <article class="box post">
            <form insung_num = 'insung_num' skill_num="skill_num" level = "level" action="{% url 'audiotest:main' %}" method = "post">
                {% csrf_token %}
                <h3>면접 세팅</h3>
                <br>
                <b>
                <h4>1. 문항의 수를 정해주세요. 단, 전체 문항 수는 인성면접, 기술면접 각 최대 10문항까지 가능합니다.</h4><br>
                인성면접 질문 수
                <input type="radio" name="insung_num" value="0"> 0
                <input type="radio" name="insung_num" value="1"> 1
                <input type="radio" name="insung_num" value="2"> 2
                <input type="radio" name="insung_num" value="3"> 3
                <input type="radio" name="insung_num" value="4"> 4
                <input type="radio" name="insung_num" value="5"> 5
                <input type="radio" name="insung_num" value="6"> 6
                <input type="radio" name="insung_num" value="7"> 7
                <input type="radio" name="insung_num" value="8"> 8
                <input type="radio" name="insung_num" value="9"> 9
                <input type="radio" name="insung_num" value="10"> 10
                <br> 기술면접 질문 수
                <input type="radio" name="skill_num" value="0"> 0
                <input type="radio" name="skill_num" value="1"> 1
                <input type="radio" name="skill_num" value="2"> 2
                <input type="radio" name="skill_num" value="3"> 3
                <input type="radio" name="skill_num" value="4"> 4
                <input type="radio" name="skill_num" value="5"> 5
                <input type="radio" name="skill_num" value="6"> 6
                <input type="radio" name="skill_num" value="7"> 7
                <input type="radio" name="skill_num" value="8"> 8
                <input type="radio" name="skill_num" value="9"> 9
                <input type="radio" name="skill_num" value="10"> 10
                <br><br><br>
                <h4>2. 기술 면접의 난이도를 설정해주세요.</h4><br>
                <input type="radio" name="level" value="0"> 하
                <input type="radio" name="level" value="1"> 중
                <input type="radio" name="level" value="2"> 상
                <br>
                <br>
                </b>
                <button type="submit" onclick="send();" align="center"> 전송 </button>
            </form>
        </article>
    </div>
</section>

{% endblock %}

templates/mainpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <!-- css 파일 호출 -->
        <link rel="stylesheet" type="text/css" href="{% static 'assets/css/main.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'multi.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-utilities.rtl.css' %}">
        <!-- JavaScript 파일 호출 -->
        <script src="{% static 'assets/js/jquery.min.js' %}"></script>
        <script src="{% static 'assets/js/jquery.dropotron.min.js' %}"></script>
        <script src="{% static 'assets/js/browser.min.js' %}"></script>
        <script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
        <script src="{% static 'assets/js/util.js' %}"></script>
        <script src="{% static 'assets/js/main.js' %}"></script>
        <title> Multicampus Group Project </title>
    </head>
    <body class="homepage is-preload">
    <div id="page-wrapper">
        <!-- 화면에 출력되지 않은 페이지에 대한 메인버튼 class: undefined -->
        <!-- 이하 각 화면 내용 출력 -->
        {% block content%}
        {% endblock %}
        <!-- 이상 각 화면 내용 -->
        {% block script %}
        {% endblock %}
    </div>
    </body>
</html>

templates/mypage_history.html
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="{% static 'multi.css' %}">
        <title> Multicampus Group Project </title>
    </head>
    <body>
        <div class="main_title" align="center">
            <form>
                <button type="button" class="title_button" onclick="location.href='{% url 'index' %}'"> jUmP </button>
            </form>
        </div>
        <div class="main_button_line" align="center">
            <form>
                <button type="button" class="main_buttons" onclick="location.href='{% url 'index' %}'"> 소개 </button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <button type="button" class="main_buttons" onclick="location.href='{% url 'interview' %}'"> 면접준비 </button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <button type="button" class="main_buttons" onclick="location.href='{% url 'docu:index' %}'"> 면접자료 </button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <button type="button" class="main_buttons" onclick="location.href='{% url 'privacy' %}'"> 마이페이지 </button>
            </form>
        </div>
        <div class="mypage">
            <div class="mypage_buttonline">
                <form>
                    <button type="button" class="mypage_button" onclick="location.href='{% url 'privacy' %}'"> </button>
                    <button type="button" class="mypage_button" onclick="location.href='{% url 'privacy' %}'"> 개인정보 확인 </button>
                    <button type="button" class="mypage_button" onclick="location.href='{% url 'history' %}'"> 면접 히스토리 </button>
                </form>
            </div>
            <div class="mypage_box">
                여기에 면접 별 동영상 나올 것
            </div>
        </div>
        <script type="text/javascript">
        </script>
    </body>
</html>

templates/mypage_privacy.html
{% extends "mainpage.html" %}

{% block content %}

<section id="header">
    <h1><a href="{% url 'index' %}">jUmP</a></h1>
    <nav id="nav">
        <ul>
            <li id="btn_home"><a href="{% url 'audiotest:index' %}">Home</a></li>
            <li id="btn_interview"><a href="{% url 'audiotest:interview' %}">Interview</a></li>
            <li id="btn_employment_info"><a href="{% url 'docu:index' %}">Employment info.</a></li>
            <li class="current" id="btn_mypage"><a href="{% url 'audiotest:privacy' %}">Mypage</a></li>
            <li id="btn_logout"><a href="{% url 'audiotest:logout' %}">Logout</a></li>
        </ul>
    </nav>
</section>
<section id="main">
    <div class="container">
        <article class="box post">
            <div class="container">
                <form method="POST" action="{% url 'audiotest:re_password' %}">
                    {% csrf_token %}
                    현재 비밀번호 :
                    <input name="origin_password" type="password">
                    <br><br>
                    변경할 비밀번호 :
                    <input name="new_password" type="password">
                    <br><br>
                    비밀번호 확인 :
                    <input name="confirm_password" type="password">
                    <br><br>
                    <input class="btn btn-primary" onclick="send()" type="submit" value="변경">
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </form>
            </div>
        </article>
    </div>
</section>

<script>
    function send(){
        alert("제출되었습니다.");
        document.getElementById("contents").submit();
    }
</script>

{% endblock %}